In [2]:
# to mount google drive
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [3]:

import pandas as pd

In [4]:
readdf1 = pd.read_csv("drive/My Drive/NSE_1_TO_50_start_to_15082020.csv")
readdf2 = pd.read_csv("drive/My Drive/NSE_51_TO_100_start_to_15082020.csv")
readdf3 = pd.read_csv("drive/My Drive/NSE_101_TO_150_start_to_15082020.csv")
readdf4 = pd.read_csv("drive/My Drive/NSE_151_TO_200_start_to_15082020.csv")
readdf5 = pd.read_csv("drive/My Drive/NSE_201_TO_250_start_to_15082020.csv")
readdf6 = pd.read_csv("drive/My Drive/NSE_251_TO_300_start_to_15082020.csv")
readdf7 = pd.read_csv("drive/My Drive/NSE_301_TO_350_start_to_15082020.csv")
readdf8 = pd.read_csv("drive/My Drive/NSE_351_TO_400_start_to_15082020.csv")
readdf9 = pd.read_csv("drive/My Drive/NSE_401_TO_450_start_to_15082020.csv")
readdf10 = pd.read_csv("drive/My Drive/NSE_451_TO_500_start_to_15082020.csv")
readdf11 = pd.read_csv("drive/My Drive/NSE_501_TO_550_start_to_15082020.csv")
readdf12 = pd.read_csv("drive/My Drive/NSE_551_TO_600_start_to_15082020.csv")
readdf13 = pd.read_csv("drive/My Drive/NSE_601_TO_650_start_to_15082020.csv")
readdf14 = pd.read_csv("drive/My Drive/NSE_651_TO_700_start_to_15082020.csv")
readdf15 = pd.read_csv("drive/My Drive/NSE_701_TO_750_start_to_15082020.csv")
readdf16 = pd.read_csv("drive/My Drive/NSE_751_TO_800_start_to_15082020.csv")
readdf17 = pd.read_csv("drive/My Drive/NSE_801_TO_850_start_to_15082020.csv")
readdf18 = pd.read_csv("drive/My Drive/NSE_851_TO_900_start_to_15082020.csv")
readdf19 = pd.read_csv("drive/My Drive/NSE_901_TO_950_start_to_15082020.csv")
readdf20 = pd.read_csv("drive/My Drive/NSE_951_TO_1000_start_to_15082020.csv")
readdf21 = pd.read_csv("drive/My Drive/NSE_1001_TO_1050_start_to_15082020.csv")
readdf22 = pd.read_csv("drive/My Drive/NSE_1051_TO_1100_start_to_15082020.csv")
readdf23 = pd.read_csv("drive/My Drive/NSE_1101_TO_1150_start_to_15082020.csv")
readdf24 = pd.read_csv("drive/My Drive/NSE_1151_TO_1200_start_to_15082020.csv")
readdf25 = pd.read_csv("drive/My Drive/NSE_1201_TO_1250_start_to_15082020.csv")
readdf26 = pd.read_csv("drive/My Drive/NSE_1251_TO_1320_start_to_15082020.csv")

In [5]:
finall = pd.concat([readdf1,
readdf2,
readdf3,
readdf4,
readdf5,
readdf6,
readdf7,
readdf8,
readdf9,
readdf10,
readdf11,
readdf12,
readdf13,
readdf14,
readdf15,
readdf16,
readdf17,
readdf18,
readdf19,
readdf20,
readdf21,
readdf22,
readdf23,
readdf24,
readdf25,
readdf26])

In [6]:
finall

        Unnamed: 0        Date       High  ...     Volume  Adj Close      SYMBOL
0                0  2005-01-05  48.000000  ...    53430.0  27.258549  PRESSMN.NS
1                1  2005-01-06  37.000000  ...     9700.0  21.814053  PRESSMN.NS
2                2  2005-01-07  24.200001  ...      893.0  17.451241  PRESSMN.NS
3                3  2005-01-10  19.400000  ...     1000.0  13.989837  PRESSMN.NS
4                4  2005-01-11  15.550000  ...     1000.0  11.213504  PRESSMN.NS
...            ...         ...        ...  ...        ...        ...         ...
173963      173963  2020-08-10   0.500000  ...   873495.0   0.450000      KGL.NS
173964      173964  2020-08-11   0.500000  ...   531354.0   0.500000      KGL.NS
173965      173965  2020-08-12   0.500000  ...  1094663.0   0.450000      KGL.NS
173966      173966  2020-08-13   0.500000  ...   799606.0   0.450000      KGL.NS
173967      173967  2020-08-14   0.450000  ...  4745008.0   0.450000      KGL.NS

[3990241 rows x 9 columns]

In [7]:
finall.describe

<bound method NDFrame.describe of         Unnamed: 0        Date       High  ...     Volume  Adj Close      SYMBOL
0                0  2005-01-05  48.000000  ...    53430.0  27.258549  PRESSMN.NS
1                1  2005-01-06  37.000000  ...     9700.0  21.814053  PRESSMN.NS
2                2  2005-01-07  24.200001  ...      893.0  17.451241  PRESSMN.NS
3                3  2005-01-10  19.400000  ...     1000.0  13.989837  PRESSMN.NS
4                4  2005-01-11  15.550000  ...     1000.0  11.213504  PRESSMN.NS
...            ...         ...        ...  ...        ...        ...         ...
173963      173963  2020-08-10   0.500000  ...   873495.0   0.450000      KGL.NS
173964      173964  2020-08-11   0.500000  ...   531354.0   0.500000      KGL.NS
173965      173965  2020-08-12   0.500000  ...  1094663.0   0.450000      KGL.NS
173966      173966  2020-08-13   0.500000  ...   799606.0   0.450000      KGL.NS
173967      173967  2020-08-14   0.450000  ...  4745008.0   0.450000      KGL.NS

[3990241 rows x 9 columns]>

In [8]:
finall.describe()

         Unnamed: 0          High  ...        Volume     Adj Close
count  3.990241e+06  3.990241e+06  ...  3.990241e+06  3.990241e+06
mean   7.744237e+04  3.171122e+02  ...  1.331576e+06  2.916988e+02
std    4.548843e+04  1.542732e+03  ...  1.047857e+07  1.501589e+03
min    0.000000e+00  5.000000e-02  ...  0.000000e+00 -1.312956e+02
25%    3.836700e+04  2.775000e+01  ...  1.133100e+04  2.119274e+01
50%    7.673500e+04  7.890000e+01  ...  6.779200e+04  6.597340e+01
75%    1.151030e+05  2.270000e+02  ...  4.410540e+05  2.000990e+02
max    1.760160e+05  8.142600e+04  ...  4.097564e+09  8.065410e+04

[8 rows x 7 columns]

In [9]:
finall.columns

Index(['Unnamed: 0', 'Date', 'High', 'Low', 'Open', 'Close', 'Volume',
       'Adj Close', 'SYMBOL'],
      dtype='object')

In [10]:
#starting date from all stocks
min(finall['Date'])

'1991-01-02'

In [11]:
#to know which stock having more number of records
finall[['SYMBOL','Date']].groupby('SYMBOL').count().reset_index().sort_values('Date', ascending=False)
#here Date is dummy record

             SYMBOL  Date
1159  TATAMOTORS.NS  7137
485     HINDALCO.NS  6100
1152    TATACHEM.NS  6088
570          ITC.NS  6083
246        CIPLA.NS  6083
...             ...   ...
940     RAJRATAN.NS    60
9      AARTISURF.NS    24
191      BOROLTD.NS    18
980      ROSSARI.NS    17
807      NDRAUTO.NS    12

[1316 rows x 2 columns]

In [12]:
#to know which stock is older one
finall['Date'] = pd.to_datetime(finall['Date'])
finall[['SYMBOL','Date']].groupby('SYMBOL').min().reset_index().sort_values('Date', ascending=True)

             SYMBOL       Date
1159  TATAMOTORS.NS 1991-01-02
1161   TATAPOWER.NS 1996-01-01
246        CIPLA.NS 1996-01-01
485     HINDALCO.NS 1996-01-01
317      DRREDDY.NS 1996-01-01
...             ...        ...
940     RAJRATAN.NS 2020-05-22
9      AARTISURF.NS 2020-07-14
191      BOROLTD.NS 2020-07-22
980      ROSSARI.NS 2020-07-23
807      NDRAUTO.NS 2020-07-30

[1316 rows x 2 columns]

In [13]:
finall['year'] = pd.DatetimeIndex(finall['Date']).year
finall['month'] = pd.DatetimeIndex(finall['Date']).month
finall['day'] = pd.DatetimeIndex(finall['Date']).day
finall['week'] = finall['Date'].dt.week
finall['day_name'] = finall['Date'].dt.day_name()

In [14]:
finall

        Unnamed: 0       Date       High  ...  day  week   day_name
0                0 2005-01-05  48.000000  ...    5     1  Wednesday
1                1 2005-01-06  37.000000  ...    6     1   Thursday
2                2 2005-01-07  24.200001  ...    7     1     Friday
3                3 2005-01-10  19.400000  ...   10     2     Monday
4                4 2005-01-11  15.550000  ...   11     2    Tuesday
...            ...        ...        ...  ...  ...   ...        ...
173963      173963 2020-08-10   0.500000  ...   10    33     Monday
173964      173964 2020-08-11   0.500000  ...   11    33    Tuesday
173965      173965 2020-08-12   0.500000  ...   12    33  Wednesday
173966      173966 2020-08-13   0.500000  ...   13    33   Thursday
173967      173967 2020-08-14   0.450000  ...   14    33     Friday

[3990241 rows x 14 columns]

In [15]:
#to know which year which stock having more records
finall[['SYMBOL','Date','year']].groupby(['SYMBOL','year']).count().reset_index().sort_values('Date', ascending=False)
#here Date is dummy record

              SYMBOL  year  Date
7770   JAYBARMARU.NS  2004   262
2630     CADILAHC.NS  2004   262
6637       HONAUT.NS  2004   262
11528  PANACEABIO.NS  2004   262
1646   BALAJITELE.NS  2004   262
...              ...   ...   ...
4129       ECLERX.NS  2007     1
1949          BCG.NS  2016     1
1304       ASTRON.NS  2017     1
4093     DWARKESH.NS  2004     1
9750     MARKSANS.NS  2002     1

[17456 rows x 3 columns]

In [16]:
finall['Volume'].max()

4097564000.0

In [17]:
#to know which stock has more  volumn

finall[['SYMBOL','Volume']].groupby('SYMBOL').max().reset_index().sort_values('Volume', ascending=False)

             SYMBOL        Volume
359      FCSSOFT.NS  4.097564e+09
458      HAVELLS.NS  3.072938e+09
184    BLKASHYAP.NS  2.400085e+09
570          ITC.NS  1.294168e+09
1095        SPYL.NS  1.193472e+09
...             ...           ...
894   PILANIINVS.NS  8.150100e+04
373    FOSECOIND.NS  8.027600e+04
1042  SHARDAMOTR.NS  7.869600e+04
186    BLUECOAST.NS  5.480000e+04
1187  THOMASCOTT.NS  4.510400e+04

[1316 rows x 2 columns]

In [18]:
finall.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3990241 entries, 0 to 173967
Data columns (total 14 columns):
 #   Column      Dtype
---  ------      -----
 0   Unnamed: 0  int64
 1   Date        datetime64[ns]
 2   High        float64
 3   Low         float64
 4   Open        float64
 5   Close       float64
 6   Volume      float64
 7   Adj Close   float64
 8   SYMBOL      object
 9   year        int64
 10  month       int64
 11  day         int64
 12  week        int64
 13  day_name    object
dtypes: datetime64[ns](1), float64(6), int64(5), object(2)
memory usage: 456.6+ MB

In [19]:
finall

        Unnamed: 0       Date       High  ...  day  week   day_name
0                0 2005-01-05  48.000000  ...    5     1  Wednesday
1                1 2005-01-06  37.000000  ...    6     1   Thursday
2                2 2005-01-07  24.200001  ...    7     1     Friday
3                3 2005-01-10  19.400000  ...   10     2     Monday
4                4 2005-01-11  15.550000  ...   11     2    Tuesday
...            ...        ...        ...  ...  ...   ...        ...
173963      173963 2020-08-10   0.500000  ...   10    33     Monday
173964      173964 2020-08-11   0.500000  ...   11    33    Tuesday
173965      173965 2020-08-12   0.500000  ...   12    33  Wednesday
173966      173966 2020-08-13   0.500000  ...   13    33   Thursday
173967      173967 2020-08-14   0.450000  ...   14    33     Friday

[3990241 rows x 14 columns]

In [20]:
finall['High_Open'] = finall['High'] - finall['Open']
finall['Open_Low'] = finall['Open'] - finall['Low']
finall['High_Low'] = finall['High'] - finall['Low']

finall['Open_Close'] = finall['Open'] - finall['Close']
finall['High_Close'] = finall['High'] - finall['Close']
finall['Close_Low'] = finall['Close'] - finall['Low']

In [21]:
finall

        Unnamed: 0       Date       High  ...  Open_Close  High_Close  Close_Low
0                0 2005-01-05  48.000000  ...  -29.799999   10.200001  29.799999
1                1 2005-01-06  37.000000  ...    6.750000    6.750000   0.000000
2                2 2005-01-07  24.200001  ...    0.000000    0.000000   0.000000
3                3 2005-01-10  19.400000  ...    0.000000    0.000000   0.000000
4                4 2005-01-11  15.550000  ...    0.000000    0.000000   0.000000
...            ...        ...        ...  ...         ...         ...        ...
173963      173963 2020-08-10   0.500000  ...    0.050000    0.050000   0.000000
173964      173964 2020-08-11   0.500000  ...    0.000000    0.000000   0.050000
173965      173965 2020-08-12   0.500000  ...    0.000000    0.050000   0.000000
173966      173966 2020-08-13   0.500000  ...    0.050000    0.050000   0.050000
173967      173967 2020-08-14   0.450000  ...    0.000000    0.000000   0.050000

[3990241 rows x 20 columns]

In [22]:
finall[['day_name']].drop_duplicates(['day_name'])

    day_name
0  Wednesday
1   Thursday
2     Friday
3     Monday
4    Tuesday

In [23]:
finall['%_change'] = ((finall['Close'] - finall['Open'])/finall['Open'])*100
#finall['%_change'] = finall['Close']*100/finall['Open']

In [24]:
finall

        Unnamed: 0       Date       High  ...  High_Close  Close_Low    %_change
0                0 2005-01-05  48.000000  ...   10.200001  29.799999  372.499990
1                1 2005-01-06  37.000000  ...    6.750000   0.000000  -18.243243
2                2 2005-01-07  24.200001  ...    0.000000   0.000000    0.000000
3                3 2005-01-10  19.400000  ...    0.000000   0.000000    0.000000
4                4 2005-01-11  15.550000  ...    0.000000   0.000000    0.000000
...            ...        ...        ...  ...         ...        ...         ...
173963      173963 2020-08-10   0.500000  ...    0.050000   0.000000  -10.000002
173964      173964 2020-08-11   0.500000  ...    0.000000   0.050000    0.000000
173965      173965 2020-08-12   0.500000  ...    0.050000   0.000000    0.000000
173966      173966 2020-08-13   0.500000  ...    0.050000   0.050000  -10.000002
173967      173967 2020-08-14   0.450000  ...    0.000000   0.050000    0.000000

[3990241 rows x 21 columns]

#HAVE TO CALCULATE PREVIOUS CLOSE